// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcP56pGO7H476RSJ3mb8gIzj6qnJU5Big',
    appId: '1:863957161247:web:12de0853eae2c28744cc2a',
    messagingSenderId: '863957161247',
    projectId: 'justicecooporate',
    authDomain: 'justicecooporate.firebaseapp.com',
    storageBucket: 'justicecooporate.firebasestorage.app',
    measurementId: 'G-5WHY4FV3E8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyVu2j0uhhhdq326QVGYJTUyJ4q6mao9g',
    appId: '1:863957161247:android:17a995cb6dfbff6144cc2a',
    messagingSenderId: '863957161247',
    projectId: 'justicecooporate',
    storageBucket: 'justicecooporate.firebasestorage.app',
  );

}